// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations.Hobby
{
    [DbContext(typeof(HobbyContext))]
    partial class HobbyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFavoriteHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyYouLikeThem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteHobby = "Basketball",
                            FullName = "Michael Ahlers",
                            SecondFavoriteHobby = "Baseball",
                            WhyYouLikeThem = "I like staying active"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteHobby = "Fishing",
                            FullName = "Josh Anness",
                            SecondFavoriteHobby = "Basketball",
                            WhyYouLikeThem = "I like being outside and staying active"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteHobby = "Cooking",
                            FullName = "Jeffrey Wallace",
                            SecondFavoriteHobby = "Photography",
                            WhyYouLikeThem = "I like exploring"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteHobby = "Cooking",
                            FullName = "Darrion Hoard",
                            SecondFavoriteHobby = "Jiu Jitsu",
                            WhyYouLikeThem = "I love to eat and learning new submission points"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
