// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations.Course
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Course", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = "IT3080",
                            CourseName = "Contemporary Programming",
                            FullName = "Michael Ahlers",
                            ProfessorName = "Dyllon Dekok"
                        },
                        new
                        {
                            Id = 2,
                            CourseID = "IT3080",
                            CourseName = "Contemporary Programming",
                            FullName = "Josh Anness",
                            ProfessorName = "Dyllon Dekok"
                        },
                        new
                        {
                            Id = 3,
                            CourseID = "IT3045",
                            CourseName = "Database Management II",
                            FullName = "Jeffrey Wallace",
                            ProfessorName = "Aditty Mutsuddi"
                        },
                        new
                        {
                            Id = 4,
                            CourseID = "IT3045",
                            CourseName = "Database Management II",
                            FullName = "Darrion Hoard",
                            ProfessorName = "Professor D"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
