// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations.Food
{
    [DbContext(typeof(FoodContext))]
    partial class FoodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Food", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMealTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteFood = "Pizza",
                            FavoriteMealTime = "Lunch",
                            FullName = "Michael Ahlers",
                            SecondFavoriteFood = "Wings"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteFood = "Burger",
                            FavoriteMealTime = "Dinner",
                            FullName = "Josh Anness",
                            SecondFavoriteFood = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteFood = "Cooking",
                            FavoriteMealTime = "I like exploring",
                            FullName = "Jeffrey Wallace",
                            SecondFavoriteFood = "Photography"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteFood = "Cooking",
                            FavoriteMealTime = "I love to eat and learning new submission points",
                            FullName = "Darrion Hoard",
                            SecondFavoriteFood = "Jiu Jitsu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
